
import com.sun.glass.events.KeyEvent;
import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author v1n1c1u5
 */
public class TelaFollow extends javax.swing.JDialog {
    private Usuario userLog;
    private String IP;
    /**
     * Creates new form TelaFollow
     */
    public TelaFollow(java.awt.Frame parent, boolean modal, Usuario user, String ip) {
        super(parent, modal);
        initComponents();
        
        userLog = user;
        IP = ip;

        DefaultComboBoxModel comboModel = (DefaultComboBoxModel) cbNomes.getModel();
        comboModel.removeAllElements();

        List<Usuario> listas = new ArrayList<>();
        try {
            ServidorChat chat = (ServidorChat) Naming.lookup("rmi://"+IP+":1098/ServidorChat");
            listas = chat.followMembros(userLog,IP);
            for (int i = 0; i < chat.followMembros(userLog,IP).size(); i++) {
                    Usuario lista = listas.get(i);
                    comboModel.addElement(lista);
            }
        } catch (NotBoundException ex) {
            Logger.getLogger(TelaSubscribe.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(TelaSubscribe.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(TelaSubscribe.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void unFollow(){
        Usuario sub = (Usuario) cbNomes.getSelectedItem();
        //JOptionPane.showMessageDialog(null, userLog.getId());
        Subscribe user = new Subscribe(userLog.getId(), sub.getId());
        try {
            ServidorChat chat = (ServidorChat) Naming.lookup("rmi://"+IP+":1098/ServidorChat");
            chat.Follow(user,IP);
            JOptionPane.showMessageDialog(null, "Follow realizado com sucesso.");
            this.dispose();
        } catch (NotBoundException ex) {
            Logger.getLogger(TelaSubscribe.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(TelaSubscribe.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(TelaSubscribe.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbNomes = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnFollow = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Unfollow");

        cbNomes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbNomes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNomesActionPerformed(evt);
            }
        });

        jLabel1.setText("Deixar de seguir");

        btnFollow.setMnemonic('f');
        btnFollow.setText("Unfollow");
        btnFollow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFollowActionPerformed(evt);
            }
        });
        btnFollow.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnFollowKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbNomes, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFollow)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbNomes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnFollow)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbNomesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNomesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbNomesActionPerformed

    private void btnFollowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFollowActionPerformed
        unFollow();
    }//GEN-LAST:event_btnFollowActionPerformed

    private void btnFollowKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnFollowKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            unFollow();
        }
    }//GEN-LAST:event_btnFollowKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFollow;
    private javax.swing.JComboBox<String> cbNomes;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
